#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
resources_file="$script_dir/.env.resources"
compose_file="$script_dir/compose.yaml"

mem_limit="2G"
cpu_limit="1"
host_git_user_name="$(git config --global --get user.name 2>/dev/null || true)"
host_git_user_email="$(git config --global --get user.email 2>/dev/null || true)"

escape_yaml_double_quoted() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s' "$value"
}

if [ -f "$resources_file" ]; then
  while IFS='=' read -r key value; do
    case "$key" in
      ""|\#*)
        continue
        ;;
      MEM_LIMIT)
        mem_limit="${value}"
        ;;
      CPU_LIMIT)
        cpu_limit="${value}"
        ;;
    esac
  done < "$resources_file"
fi

host_gnupg_dir="${HOME}/.gnupg"
host_gpg_agent_extra_socket="$(gpgconf --list-dir agent-extra-socket 2>/dev/null || true)"
host_ssh_dir="${HOME}/.ssh"
host_ssh_auth_sock="${SSH_AUTH_SOCK:-}"
host_ssh_config="${host_ssh_dir}/config"
host_ssh_known_hosts="${host_ssh_dir}/known_hosts"

compose_volumes=(
  '      - "..:/workspaces/datalake-pdf:cached"'
)
compose_environment=()

if [ -n "$host_git_user_name" ] && [ -n "$host_git_user_email" ]; then
  compose_environment+=(
    "      HOST_GIT_USER_NAME: \"$(escape_yaml_double_quoted "$host_git_user_name")\""
    "      HOST_GIT_USER_EMAIL: \"$(escape_yaml_double_quoted "$host_git_user_email")\""
  )
else
  printf '%s\n' \
    "[devcontainer] Host Git identity not found in git config --global." \
    "[devcontainer] The container will start without user.name and user.email configured." \
    >&2
fi

if [ -d "$host_gnupg_dir" ] && [ -S "$host_gpg_agent_extra_socket" ]; then
  compose_volumes+=(
    "      - \"$(escape_yaml_double_quoted "${host_gnupg_dir}:/home/vscode/.host-gnupg:ro")\""
    "      - \"$(escape_yaml_double_quoted "${host_gpg_agent_extra_socket}:/home/vscode/.gnupg/S.gpg-agent")\""
  )
else

  printf '%s\n' \
    "[devcontainer] Host GPG forwarding disabled: missing ~/.gnupg or agent extra socket." \
    "[devcontainer] Commits inside the container will not be GPG-signed until the host agent is available." \
    >&2
fi

if [ -n "$host_ssh_auth_sock" ] && [ -S "$host_ssh_auth_sock" ]; then
  compose_volumes+=(
    "      - \"$(escape_yaml_double_quoted "${host_ssh_auth_sock}:/tmp/ssh-agent.sock")\""
  )
  compose_environment+=(
    "      SSH_AUTH_SOCK: /tmp/ssh-agent.sock"
  )
else
  printf '%s\n' \
    "[devcontainer] Host SSH agent forwarding disabled: SSH_AUTH_SOCK is not available." \
    "[devcontainer] SSH remotes may require credentials configured directly inside the container." \
    >&2
fi

if [ -f "$host_ssh_config" ]; then
  compose_volumes+=(
    "      - \"$(escape_yaml_double_quoted "${host_ssh_config}:/home/vscode/.host-ssh/config:ro")\""
  )
fi

if [ -f "$host_ssh_known_hosts" ]; then
  compose_volumes+=(
    "      - \"$(escape_yaml_double_quoted "${host_ssh_known_hosts}:/home/vscode/.host-ssh/known_hosts:ro")\""
  )
fi

{
  printf '%s\n' \
    '# Generated by .devcontainer/initialize-host-env.sh' \
    'services:' \
    '  devcontainer:' \
    '    build:' \
    '      context: ..' \
    '      dockerfile: .devcontainer/Dockerfile' \
    "    mem_limit: ${mem_limit}" \
    "    cpus: '${cpu_limit}'"

  if [ ${#compose_environment[@]} -gt 0 ]; then
    printf '%s\n' '    environment:'
    printf '%s\n' "${compose_environment[@]}"
  fi

  printf '%s\n' '    volumes:'
  printf '%s\n' "${compose_volumes[@]}"
  printf '%s\n' '' '    command: sleep infinity'
} > "$compose_file"
